# Specify Node Version and Image
# Name Image development (can be anything)
FROM node:14 as development

# Specify Working directory inside container
WORKDIR /src/app

# Copy package-lock.json & package.json from host to inside container working directory
COPY package*.json ./
COPY . .

# Install deps inside container
RUN npm install

RUN npm run build

EXPOSE 3000

# run app
CMD [ "node", "dist/main"]